trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndRunDockerImage
  steps:
  - checkout: self
        
  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
        command: test
        projects: $(solution)
        arguments: --configuration Release --logger trx --collect:"XPlat Code Coverage"
