name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      working-directory: Src/
      run: dotnet restore 

    - name: Build
      working-directory: Src/
      run: dotnet build --no-restore

    - name: Test
      working-directory: Src/
      run: dotnet test --configuration Release --no-build --verbosity normal